### ISSUE TITLE
Feature requests to assist in migrating from 5 bots.

### ISSUE THREAD

**Issue by KiriCattus** [neoforged/Camelot#1]
List of features Camelot needs before I can start to switch over:
Note: Any commands that are out of scope/undesired can always be put into another bot of mine to save command space being used up, please mark any such commands with an X so I know)

**LOGGING:**
- [x] should be able to turn it on and off with a command: e.g. ``/logging joins-and-leaves disable`` or ``/logging moderation disabled`` (Useful for if we want to prune or no longer need that feature etc) 
- [x] user join/leave events
- [x] moderation events
- [x] deleted/edited messages (Not planned that I'm aware of so I've my own mini python bot to cover this)

**MODERATION:**
- [x] warnings/strikes or both for a 6 warn 3 strikes your out system.
- [x] moderation based commands (I'm told these are already implemented but I'd like a list if possible please)

**INFORMATION:**
- [x] ~~catfacts~~ (not used)
- [x] ~~dogfacts~~ (not used)
- [x] guild information (trick)
- [x] user information (trick)
- [x] mc-age
- [x] invites
- [x] help commands (``/help`` or ``/commands`` ect)
- [x] ~~search (LMGTFY/Google/bing/yahoo/whatever else people feel cursed enough to use)~~ Can be a trick
toggles)
- [x] rules/rule (``/rule 4`` Quote any rule from the servers rules, may not be required anymore I forgot what Maty said about this one...)
- [x] message-referencing (Bot converts a message link into an embed quoting the user and what they said, also useful for ``rule 4`` to replace it maybe?)
- [x] gist/paste (For crash reports or sharing code)

**MISC:**
- [x] quotes
- [x] reminders
- [x] custom pings
- [x] tricks

**APPS:**
- [x] add quote (adds a quote without having to use the ``/quote add`` command
- [x] gist (uploads a code/text file to gist)

If needed, certain features can be denied and added into a separate bot altogether since I do need to keep a few unique tools that you more than likely won't need.
A one time DB conversion tool may be required to convert our existing tricks, quotes, custom pings and warnings (More specifically a Maty/sci job since they know the existing bot system the three of us use elsewhere)

**Comment by TheCurle** [comment]
> catfacts
dogfacts
guild information
user information
mc-age
invites
help commands (/help or /commands ect)
search (LMGTFY/Google/bing/yahoo/whatever else people feel cursed enough to use)
version commands for different loaders/mc versions/mappings (Make different loaders/mappings enable/disable toggles)

These can all be done via tricks, and do not need to be core commands in the bot.

**Comment by KiriCattus** [comment]
"version" I assumed would just go along side the announcement code since it already exists and checks using the auto checkers code.
"help" Commands generally I've only ever seen done and hard coded but if you can get it to work as a shipped trick then great :)

**Comment by Matyrobbrt** [comment]
I would not expose any HTTP APIs in the trick dsl purely because it can be easily abused.
