### ISSUE TITLE
Add way to directly see quote when using Apps > Add Quote

### ISSUE THREAD

**Issue by PlatinPython** [neoforged/Camelot#8]
Currently when someone quotes a message using Apps > Add Quote the only information others get is the number with which the quote was added and who did the quoting. It would be nice if one could directly find out what exactly was quoted without first going through `/quote get`.

**Comment by PlatinPython** [comment]
Ok, was implemented in https://github.com/neoforged/Camelot/commit/4f3943c137e5af5f35a88ec273a96bbf236eac76

**Comment by Matyrobbrt** [comment]
Closed by https://github.com/neoforged/Camelot/commit/4f3943c137e5af5f35a88ec273a96bbf236eac76
